#!/bin/bash
#
i=0
for f in *; 
do
  if [ -f "$f" ]; then
    for((i='a';i<'z';i++))
    do
        i+=1
        printf $i

    done
    #printf $f | wc -c
    #printf $f | wc -c
    #echo "$f is a directory"
  fi
done
