#!/bin/bash
# Create a script
mkdir /home/parallels/myexec
# $_
cd /home/parallels/myexec/
echo pwd
echo echo $(date) > shadi
chmod 700 shadi
echo PATH=/home/parallels/myexec:$PATH >> ~/.zshrc
echo 'alias installer_shadi="./installer"' >> ~/.zshrc
