#!/bin/bash
#
if [[ $1 == "+" ]];then
    i=0;
    # + 10 2 2 1
    # ${@:2} -> start from 10
    for num in ${@:2} 
    do
        (( i += $num ))

    done
elif [[ $1 == "-" ]];then
    # add 10 to var(i)
    i=$2
    # - 10 2 2 1
    # ${@:3} -> start from 2
    for num in ${@:3}
    do
        (( i -= $num ))
    done
fi
echo $i
