#!/bin/bash
#

if [ -f output.txt ]; then
    rm -r output.txt
fi

sed 's/a//g' data.txt >> output.txt
cat output.txt


"""
Question
Loop over a test file and remove the letter (lowercase) m.
Send everything except m into the standard output.
"""