#!/bin/bash
#
# One way
str="$1"
reversed_string=""
# finding the length of string
len=${#str}
# traverse the string in reverse order.
for (( i=$len-1; i>=0; i-- ))
do
   reversed_string="$reversed_string${str:$i:1}"
done
# printing the reversed string.
echo "$reversed_string"


# Another way
#echo $1 | sed 's/./&\n/g' | tac | sed -e :a -e 'N;s/\n//g;ta'



#"""
#Question
#print a string and reverse it
#"""